version: "3"
services:
    app:
        env_file:
            - .env
        ports:
            -   "127.0.0.1:5000:5000"
            -   "127.0.0.1:5022:22"
        build: 
            context: .
            dockerfile: Dockerfile_app
        deploy:
            resources:
                limits:
                    cpus: '2'

    tester:
        build: 
            context: .
            dockerfile: Dockerfile_tester
        depends_on:
            - app
