FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    git=1:2.34.1-1ubuntu1.8 \
    python3=3.10.6-1~22.04 \
    python3-pip=22.0.2+dfsg-1ubuntu0.2 \
    openssh-server=1:8.9p1-3ubuntu0.1

RUN sed -i '/PermitRootLogin prohibit-password/c\PermitRootLogin yes' /etc/ssh/sshd_config 

COPY id_rsa.pub /root/.ssh/authorized_keys

COPY requirements.txt .
RUN pip3 install -r requirements.txt

RUN git clone https://github.com/moevm/devops-examples.git
WORKDIR devops-examples/EXAMPLE_APP/

COPY add_host.patch  start.sh ./
RUN patch main.py add_host.patch

ENTRYPOINT ["sh", "./start.sh"]
